### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by sanliturk** [kyouko-taiga/Alpine#1]
There is NO any license file or information about your repository . If there is no any license information , with respect to copyrights laws and international treaties it is not possible to use your repository sources .

Thank you for your very nice works .

Mehmet Erol Sanliturk

**Comment by kyouko-taiga** [comment]
Hello Mehmet.

Thanks for raising that issue. I've applied the MIT license to that repository.
Cheers!

**Comment by sanliturk** [comment]
Thank you very much .
With my best wishes for you and all of humanity .
Mehmet Erol Sanliturk
